name = "pubs"
version = "0.1.0"
defaultTargets = ["pubs"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[lean_lib]]
name = "Pubs"

[[lean_exe]]
name = "pubs"
root = "Main"

[[require]]
name = "markdown"
git = "https://github.com/gmcninch-prof/lean4-markdown"
rev = "gm-extensions"
  