name = "msdata"
version = "0.1.0"
defaultTargets = ["msdata"]

[[lean_lib]]
name = "Msdata"

[[lean_exe]]
name = "msdata"
root = "Main"

[[require]]
name = "markdown"
git = "https://github.com/predictable-machines/lean4-markdown"
rev = "v0.1.0"
  